variables:
        BINARY: $CI_PROJECT_NAME
        BUILD_DIR: "builds"
        GO111MODULE: "on"
        CMD_DIR: "cmd/bp/main.go"

.init_go: &init_go
        before_script:
                - export GL_URL=$(echo $CI_PROJECT_URL | awk -F/ '{print $3}')
                - export GO_PROJECT_PATH="$GOPATH/src/$GL_URL/$CI_PROJECT_NAMESPACE"
                - mkdir -p $GO_PROJECT_PATH
                - ln -s $(pwd) $GO_PROJECT_PATH
                - export GO_PROJECT_PATH="$GO_PROJECT_PATH/$CI_PROJECT_NAME"
                - cd $GO_PROJECT_PATH
                - apk add git

stages:
        - build

go_build:
        <<: *init_go
        stage: build
        image: golang:1.14-alpine
        script:
                - mkdir $BUILD_DIR
                - export CGO_ENABLED=0 GOOS=freebsd GOARCH=386
                - go build -o $BUILD_DIR/$BINARY-$GOARCH $CMD_DIR
                - export GOARCH=amd64
                - go build -o $BUILD_DIR/$BINARY-$GOARCH $CMD_DIR
        artifacts:
                paths:
                        - $BUILD_DIR/
